import React, { useState } from "react";
import { NavLink } from "react-router-dom";
import { Check, ChevronDown, Pencil } from "lucide-react";
import { TopBar } from "@/components/TopBar";

const employee = { id: "EMP-0043", name: "Arjun Singh", initials: "AS", status: "Active" as const, role: "General Manager", department: "Management", shift: "Morning Shift" };
const tabs = ["General", "Compensation", "Attendance", "Leave"] as const;

const Compensation: React.FC = () => {
  const [compensationType, setCompensationType] = useState<"Hourly" | "Weekly" | "Monthly">("Hourly");
  const tabPath = (tab: typeof tabs[number]) => tab === "General" ? "/employee-profile" : `/employee-profile/${tab.toLowerCase()}`;

  return <div className="min-h-screen bg-slate-50 text-slate-800"><TopBar /><main className="mx-auto max-w-[1600px] px-5 py-5 sm:px-8 sm:py-6">
    <section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-lg font-bold text-emerald-700">{employee.initials}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-900">{employee.name}</h1><span className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-xs font-semibold text-emerald-700">{employee.status}</span></div><p className="mt-1 text-sm text-slate-500">{employee.role} · {employee.department} · {employee.shift}</p><p className="mt-1 text-xs text-slate-400">{employee.id}</p></div><button className="self-start rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium hover:bg-slate-50 sm:self-center">Edit Profile</button></section>
    <nav className="mt-3 flex gap-7 border-b border-slate-200 text-sm">{tabs.map((tab) => <NavLink key={tab} to={tabPath(tab)} className={({ isActive }) => `border-b-2 px-0 py-3 ${isActive ? "border-green-600 font-semibold text-green-600" : "border-transparent text-slate-500 hover:text-slate-700"}`}>{tab}</NavLink>)}</nav>
    <section className="mt-4 rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="text-xs font-bold tracking-wide text-slate-900">COMPENSATION TYPE</h2><button aria-label="Edit compensation" className="rounded-lg border border-slate-200 p-2 hover:bg-slate-50"><Pencil className="h-4 w-4 text-slate-500" /></button></header><div className="px-5"> 
      <div className="flex flex-col gap-3 border-b border-slate-100 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm text-slate-600">Compensation Type <span className="text-red-500">*</span></span><div className="w-full sm:w-[220px]"><label className="relative block"><select value={compensationType} onChange={(event) => setCompensationType(event.target.value as typeof compensationType)} className="w-full appearance-none rounded-lg border border-slate-200 bg-white px-3 py-2 pr-9 text-sm text-slate-700 outline-none focus:border-emerald-500">{tabs.slice(1).map((type) => <option key={type}>{type === "Attendance" ? "Hourly" : type === "Leave" ? "Monthly" : "Weekly"}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-2.5 h-4 w-4 text-slate-400" /></label><div className="mt-2 flex justify-end gap-1">{(["Hourly", "Weekly", "Monthly"] as const).map((type) => <button key={type} onClick={() => setCompensationType(type)} className={`rounded-full border px-2 py-1 text-xs ${compensationType === type ? "border-emerald-200 bg-emerald-50 font-semibold text-emerald-700" : "border-slate-200 text-slate-500"}`}>{compensationType === type && <Check className="mr-1 inline h-3 w-3" />}{type}</button>)}</div></div></div>
      {[[<>Hourly Rate <span className="text-red-500">*</span><small className="mt-1 block text-xs text-slate-400">Used for labor cost calculations</small></>, "$25.00/hr"], ["Monthly Salary", "—"], [<>Overtime Eligible <span className="text-red-500">*</span></>, "Yes"], ["Overtime Rate", "$37.50/hr"], [<>Effective From <span className="text-red-500">*</span></>, "Jan 01, 2025"], ["Effective To", "—"], [<>Status <span className="text-red-500">*</span></>, "Active"]].map(([label, value], index) => <div key={index} className="flex items-center justify-between gap-5 border-b border-slate-100 py-4 last:border-0"><div className="text-sm text-slate-600">{label}</div><span className={value === "—" ? "text-sm text-slate-400" : value === "Yes" || value === "Active" ? "rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-700" : "text-sm font-semibold text-slate-900"}>{value}</span></div>)}
    </div></section></main></div>;
};
export default Compensation;
