import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { HRMSLayout } from "@/components/HRMSLayout";
const holidays = [
  ["New Year's Day", "2026-01-01", "Thursday", "National"], ["Republic Day", "2026-01-26", "Monday", "National"], ["Holi", "2026-03-03", "Tuesday", "Regional"], ["Good Friday", "2026-04-03", "Friday", "National"], ["Eid al-Fitr", "2026-03-20", "Friday", "National"], ["Independence Day", "2026-08-15", "Saturday", "National"], ["Gandhi Jayanti", "2026-10-02", "Friday", "National"], ["Diwali", "2026-11-09", "Monday", "National"],
];
export default function HolidayCalendar() {
  const [query, setQuery] = useState(""); const [isAddOpen, setIsAddOpen] = useState(false);
  const rows = useMemo(() => holidays.filter(([name]) => name.toLowerCase().includes(query.toLowerCase())), [query]);
  return <HRMSLayout breadcrumb={<><span>HRMS</span><span className="mx-2 text-slate-300">/</span><span className="text-slate-900">Holiday Calendar</span></>}><main className="mx-auto max-w-[1600px] px-5 py-6 sm:px-7"><div className="mb-6 flex items-center justify-between gap-4"><h1 className="text-2xl font-bold text-slate-900">Holiday Calendar</h1><button onClick={() => setIsAddOpen(true)} className="flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-green-700"><Plus className="h-4 w-4" />Add Holiday</button></div><label className="mb-5 flex max-w-[420px] items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5"><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search holiday..." className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"/></label><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold text-slate-500"><tr>{["Holiday Name", "Date", "Day", "Type", "Applicable To", "Status", "Actions"].map((head) => <th key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody>{rows.map(([name, date, day, type]) => <tr key={name} className="border-t border-slate-100"><td className="px-4 py-3.5 font-semibold text-slate-800">{name}</td><td className="px-4 py-3.5 text-slate-600">{date}</td><td className="px-4 py-3.5 text-slate-600">{day}</td><td className={`px-4 py-3.5 font-bold ${type === "National" ? "text-rose-700" : "text-blue-600"}`}>{type}</td><td className="px-4 py-3.5 text-slate-600">All Employees</td><td className="px-4 py-3.5"><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-700">Active</span></td><td className="px-4 py-3.5"><div className="flex gap-3"><button aria-label={`Edit ${name}`} className="text-slate-500 hover:text-green-600"><Pencil className="h-4 w-4"/></button><button aria-label={`Edit ${name}`} className="text-slate-500 hover:text-green-600"><Pencil className="h-4 w-4"/></button><button aria-label={`Delete ${name}`} className="text-rose-500"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>{isAddOpen && <div onClick={() => setIsAddOpen(false)} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4 backdrop-blur-sm"><div onClick={(e) => e.stopPropagation()} className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-bold">Add Holiday</h2><p className="mt-2 text-sm text-slate-500">Holiday creation is ready for your details.</p><button onClick={() => setIsAddOpen(false)} className="mt-5 rounded-lg bg-green-600 px-4 py-2 text-sm font-semibold text-white">Close</button></div></div>}</main></HRMSLayout>;
}
